[package]
name = "workflow"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "dwf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
property = { path = "../property" }
