[package]
name = "xc"
version = "0.1.0"
authors = ["Junwen Li <junwen.li@dftworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { path = "../ndarray" }
types = { path = "../types" }
utility = { path = "../utility" }
dfttypes = { path = "../dfttypes" }
gvector = { path = "../gvector" }
pwdensity = { path = "../pwdensity" }
rgtransform = { path = "../rgtransform" }
lattice = { path = "../lattice" }
