[package]
name = "wannier90"
version = "0.1.0"
authors = ["Junwen Li <junwen.li@dftworks.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
control = { path = "../control" }
crystal = { path = "../crystal" }
dfttypes = { path = "../dfttypes" }
dwconsts = { path = "../dwconsts" }
dwmpi = { path = "../dwmpi" }
fftgrid = { path = "../fftgrid" }
fhkl = { path = "../fhkl" }
gvector = { path = "../gvector" }
integral = { path = "../integral" }
kgylm = { path = "../kgylm" }
kpts = { path = "../kpts" }
matrix = { path = "../matrix" }
mpi_sys = { path = "../mpi_sys" }
pspot = { path = "../pspot" }
pwbasis = { path = "../pwbasis" }
special = { path = "../special" }
types = { path = "../types" }
utility = { path = "../utility" }
vector3 = { path = "../vector3" }
